# enable color support of ls and also add handy aliases
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some more ls aliases
alias ls='ls --color=auto -h'
alias la='ls -AlF'
alias ll='ls -CFl'
alias l='ll'


alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias chown='chown -cf'
alias chmod='chmod -cv'
alias vi='vim -p'
alias tarx='tar -xvf'
alias tarz='tar -zcvf'
alias diff='diff -u'
#some else aliases
alias ge='gedit'
alias df='df -h'
alias ..='cd ..'
alias d='pwd'
alias free='free -h'
alias grep='grep -n'
alias c='clear'
alias tree='tree -L'
alias du='du -ch -d 1'
alias useradd='useradd -m -s /bin/bash '
alias mkdir='mkdir -p'
